config/routes.rb
Rails.application.routes.draw do

   root 'paginator#index'

   post 'index'  => 'paginator#index', as: :pages

end

app/models/number_to_word.rb
class NumberToWord


  NUMBERS = {0=>"zero", 1=>"one", 2=>"two", 3=>"three", 4=>"four", 5=>"five", 6=>"six", 7=>"seven", 8=>"eight", 9=>"nine", 10=>"ten", 11=>"eleven", 12=>"twelve", 13=>"thirteen", 14=>"fourteen", 15=>"fifteen", 16=>"sixteen", 17=>"seventeen", 18=>"eighteen", 19=>"nineteen", 20=>"twenty", 21=>"twenty one", 22=>"twenty two", 23=>"twenty three", 24=>"twenty four", 25=>"twenty five", 26=>"twenty six", 27=>"twenty seven", 28=>"twenty eight", 29=>"twenty nine", 30=>"thirty", 31=>"thirty one", 32=>"thirty two", 33=>"thirty three", 34=>"thirty four", 35=>"thirty five", 36=>"thirty six", 37=>"thirty seven", 38=>"thirty eight", 39=>"thirty nine", 40=>"forty", 41=>"forty one", 42=>"forty two", 43=>"forty three", 44=>"forty four", 45=>"forty five", 46=>"forty six", 47=>"forty seven", 48=>"forty eight", 49=>"forty nine", 50=>"fifty", 51=>"fifty one", 52=>"fifty two", 53=>"fifty three", 54=>"fifty four", 55=>"fifty five", 56=>"fifty six", 57=>"fifty seven", 58=>"fifty eight", 59=>"fifty nine", 60=>"sixty", 61=>"sixty one", 62=>"sixty two", 63=>"sixty three", 64=>"sixty four", 65=>"sixty five", 66=>"sixty six", 67=>"sixty seven", 68=>"sixty eight", 69=>"sixty nine", 70=>"seventy", 71=>"seventy one", 72=>"seventy two", 73=>"seventy three", 74=>"seventy four", 75=>"seventy five", 76=>"seventy six", 77=>"seventy seven", 78=>"seventy eight", 79=>"seventy nine", 80=>"eighty", 81=>"eighty one", 82=>"eighty two", 83=>"eighty three", 84=>"eighty four", 85=>"eighty five", 86=>"eighty six", 87=>"eighty seven", 88=>"eighty eight", 89=>"eighty nine", 90=>"ninety", 91=>"ninety one", 92=>"ninety two", 93=>"ninety three", 94=>"ninety four", 95=>"ninety five", 96=>"ninety six", 97=>"ninety seven", 98=>"ninety eight", 99=>"ninety nine"}
  DIVISORS = {100=>"hundred", 1000=>"thousand", 1000000=>"million"}
  MAX_COUNT = 1000000 #One Million

  def self.to_words(number)
    if number > 0 && number < 100
      return NUMBERS[number]
    elsif number > 0 && number <= MAX_COUNT
      (return "#{NUMBERS[1]} #{DIVISORS[1000000]}") if (number / MAX_COUNT == 1)

      numbers_array = number.divmod(1000)

      numbers_array = numbers_array.map {|e| e = "%03d" % e} #Change to string with 3 decimal places
      temp_number = ""

      unless numbers_array[0] == "000"
        if numbers_array[0][0] == "0"
          temp_number << "#{NUMBERS[numbers_array[0][1..2].to_i]} #{DIVISORS[1000]}"
        else
          temp_number << "#{NUMBERS[numbers_array[0][0].to_i]} #{DIVISORS[100]}"
          temp_number <<  " and #{NUMBERS[numbers_array[0][1..2].to_i]}" unless numbers_array[0][1..2].to_i == 0
          temp_number <<  " #{DIVISORS[1000]}"
        end
      end

      temp_number << " #{NUMBERS[numbers_array[1][0].to_i]} #{DIVISORS[100]}" unless numbers_array[1][0].to_i == 0
      temp_number << " and #{NUMBERS[numbers_array[1][1..2].to_i]}"  unless numbers_array[1][1..2].to_i == 0

      return temp_number.strip
    else
      raise TypeError.new("Number out of scope") 
    end
  end

end

app/models/paginator.rb
class Paginator

  MAX_COUNT = 1000000 #One Million

  def self.numbers_as_words(page_number, numbers_per_page)
    first_number = (page_number * numbers_per_page) + 1
    last_number = first_number + numbers_per_page

    last_number = MAX_COUNT if last_number > MAX_COUNT

    numbers = first_number.upto(last_number).map{|n| n = NumberToWord.to_words(n)}
  end



  def self.pagination_to_display(numbers_per_page, page_number)
    numbers = []
    
    page_count = total_page_count(numbers_per_page)

    if page_number > 5
      first_number = page_number - 5
    else
      first_number = 1
    end

    if page_count-2 <= page_number + 5
      last_number = page_count-2
    else
      last_number = page_number + 5
    end

    numbers << {key: 0, value: 0}

    first_number.upto(last_number).each_with_index do | number, index |
      numbers << {key: index+1, value: number}
    end

    if numbers.count != 11
      number_to_move = numbers.pop
      numbers << {key: 11, value: number_to_move[:value]}
    end

    numbers << {key: 12, value: page_count-1}

    return numbers
  end

  def self.total_page_count(numbers_per_page)
    page_count = MAX_COUNT / numbers_per_page
    (MAX_COUNT % numbers_per_page > 0) ? (return page_count+1) : (return page_count)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paginator_controller.rb
class PaginatorController < ApplicationController
  
  def index
  	if paginator_params[:numbers_per_page].present?
  		@number_per_page = paginator_params[:numbers_per_page].to_i 
  	else
  		@number_per_page = 1000
  	end

  	if paginator_params[:current_page].present?
  		current_page = paginator_params[:current_page].to_i 
  	else
  		current_page = 0
  	end

  	@pages = Paginator.pagination_to_display(@number_per_page, current_page)

    @numbers = Paginator.numbers_as_words(current_page,	@number_per_page)

    @total_pages = Paginator.total_page_count(@number_per_page)
  end

  private

  def paginator_params
    params.permit(:numbers_per_page, :current_page)
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <h4><%= link_to "Pagination Application", root_path %></h4>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaginiationLists</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/navbar' %>
    <div class="container" style="width: 40%;">
      <%= yield %>
    </div>

</body>
</html>

app/views/paginator/index.html.erb
<div class="panel-body">
  	<div class="form-group col-sm-8">
    	<div class="form-inline">
        <% @pages.each do | page | %> 
        	<% if page[:key] == 0 %>
        		<%= link_to "<<", pages_path(current_page: page[:value], numbers_per_page: @number_per_page), method: :post %>
        	<% elsif page[:key] == 1 && page[:value] != 1 %>
        		<%= link_to "<", pages_path(current_page: page[:value], numbers_per_page: @number_per_page), method: :post %>
        	<% elsif page[:key] == 11 && page[:value] != @total_pages-2 %>
        		<%= link_to ">", pages_path(current_page: page[:value], numbers_per_page: @number_per_page), method: :post %>
      		<% elsif page[:key] == 12 %>
        		<%= link_to ">>", pages_path(current_page: page[:value], numbers_per_page: @number_per_page), method: :post %>
        	<% else %>
         		<%= link_to page[:value], pages_path(current_page: page[:value], numbers_per_page: @number_per_page), method: :post %>
      	 	<% end %>
      	<% end %>
    </div>
  </div>

  <div class="form-group col-sm-4">
  	<p>Total Number Of Pages: <%= @total_pages %> </p>
  </div>

	<div class="form-group col-sm-8">
			<%= form_tag(pages_path, method: :post) do %>
				<%= label_tag :numbers_per_page %>
				<%= text_field_tag :numbers_per_page %>
				<%= submit_tag 'Change Number', current_page: nil %>
			<% end %>
		</div>
</div>

<div class="panel-body">
  <table class="table table-condensed table-hover">
    <thead>
      <tr>
        <th>Numbers</th>
      </tr>
    </thead>
    <tbody>   
      <% @numbers.each do | number | %> 
        <tr>
          <td><%= number %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>